name: Run MCQ Generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-Levenshtein  # For faster fuzzy matching

      - name: Set up Google Service Account
        # Write the CLIENT_SECRETS to a file called service_account.json
        run: echo "${{ secrets.CLIENT_SECRETS }}" > service_account.json

      - name: Run the MCQ Generator
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json  # Set the path for authentication
        run: python main.py
