name: Run MCQ Generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-Levenshtein  # For faster fuzzy matching

      - name: Set up Google Service Account
        # Write the service account JSON to a file from the CLIENT_SECRETS secret
        run: echo "${{ secrets.CLIENT_SECRETS }}" > service_account.json

      - name: Run the MCQ Generator
        env:
          CLIENT_SECRETS: ${{ secrets.CLIENT_SECRETS }}  # Load the secret as an environment variable
        run: python main.py
