name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # Specify the environment here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Decrypt the secret
      - name: Decrypt the client secret
        run: |
          echo "${{ secrets.DECRYPTION_KEY }}" > decryption_key.txt
          python3 decrypt.py

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run your application or tests
      - name: Run your code
        run: |
          python3 main.py
